//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public catalogo()
        {
            this.especiecatalogo = new HashSet<especiecatalogo>();
            this.ImagenEspecimen = new HashSet<ImagenEspecimen>();
            this.multimedia = new HashSet<multimedia>();
            this.nombrecomuncatalogo = new HashSet<nombrecomuncatalogo>();
            this.publicacioncatalogo = new HashSet<publicacioncatalogo>();
            this.publicacionenlace = new HashSet<publicacionenlace>();
            this.reptiliacatalogo = new HashSet<reptiliacatalogo>();
        }
    
        public long IdCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Sigla { get; set; }
        public string Descripcion { get; set; }
        public long IdTipoCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual tipocatalogo tipocatalogo { get; set; }
        public virtual ICollection<especiecatalogo> especiecatalogo { get; set; }
        public virtual ICollection<ImagenEspecimen> ImagenEspecimen { get; set; }
        public virtual ICollection<multimedia> multimedia { get; set; }
        public virtual ICollection<nombrecomuncatalogo> nombrecomuncatalogo { get; set; }
        public virtual ICollection<publicacioncatalogo> publicacioncatalogo { get; set; }
        public virtual ICollection<publicacionenlace> publicacionenlace { get; set; }
        public virtual ICollection<reptiliacatalogo> reptiliacatalogo { get; set; }
    }
}
