//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxa
    {
        public taxa()
        {
            this.especie = new List<especie>();
            this.especimen = new List<especimen>();
            this.multimedia = new List<multimedia>();
            this.nombrecomun = new List<nombrecomun>();
            this.ordenamientotaxa = new List<ordenamientotaxa>();
            this.sinonimo = new List<sinonimo>();
            this.taxa1 = new List<taxa>();
            this.taxapublicacion = new List<taxapublicacion>();
            this.tipo = new List<tipo>();
        }
    
        public long IdTaxa { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public bool EnEcuador { get; set; }
        public bool Endemica { get; set; }
        public Nullable<long> IdTaxaPadre { get; set; }
        public long IdCatalogo { get; set; }
        public bool PublicarEnWeb { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<long> IdPublicacionReporte { get; set; }
        public Nullable<int> Ano { get; set; }
        public string prueba { get; set; }
    
     
    }
}
