//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Interface.pub {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback seleccionarTaxaOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarTaxaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarTaxaPublicacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Interface.Properties.Settings.Default.Interface_pub_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event seleccionarTaxaCompletedEventHandler seleccionarTaxaCompleted;
        
        /// <remarks/>
        public event seleccionarTaxaPorIdCompletedEventHandler seleccionarTaxaPorIdCompleted;
        
        /// <remarks/>
        public event SeleccionarTaxaPublicacionCompletedEventHandler SeleccionarTaxaPublicacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarTaxa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxa[] seleccionarTaxa() {
            object[] results = this.Invoke("seleccionarTaxa", new object[0]);
            return ((taxa[])(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarTaxaAsync() {
            this.seleccionarTaxaAsync(null);
        }
        
        /// <remarks/>
        public void seleccionarTaxaAsync(object userState) {
            if ((this.seleccionarTaxaOperationCompleted == null)) {
                this.seleccionarTaxaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarTaxaOperationCompleted);
            }
            this.InvokeAsync("seleccionarTaxa", new object[0], this.seleccionarTaxaOperationCompleted, userState);
        }
        
        private void OnseleccionarTaxaOperationCompleted(object arg) {
            if ((this.seleccionarTaxaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarTaxaCompleted(this, new seleccionarTaxaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarTaxaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxa[] seleccionarTaxaPorId(int IdTaxa) {
            object[] results = this.Invoke("seleccionarTaxaPorId", new object[] {
                        IdTaxa});
            return ((taxa[])(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarTaxaPorIdAsync(int IdTaxa) {
            this.seleccionarTaxaPorIdAsync(IdTaxa, null);
        }
        
        /// <remarks/>
        public void seleccionarTaxaPorIdAsync(int IdTaxa, object userState) {
            if ((this.seleccionarTaxaPorIdOperationCompleted == null)) {
                this.seleccionarTaxaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarTaxaPorIdOperationCompleted);
            }
            this.InvokeAsync("seleccionarTaxaPorId", new object[] {
                        IdTaxa}, this.seleccionarTaxaPorIdOperationCompleted, userState);
        }
        
        private void OnseleccionarTaxaPorIdOperationCompleted(object arg) {
            if ((this.seleccionarTaxaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarTaxaPorIdCompleted(this, new seleccionarTaxaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarTaxaPublicacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaxaPublicacion[] SeleccionarTaxaPublicacion(long taxaid) {
            object[] results = this.Invoke("SeleccionarTaxaPublicacion", new object[] {
                        taxaid});
            return ((TaxaPublicacion[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarTaxaPublicacionAsync(long taxaid) {
            this.SeleccionarTaxaPublicacionAsync(taxaid, null);
        }
        
        /// <remarks/>
        public void SeleccionarTaxaPublicacionAsync(long taxaid, object userState) {
            if ((this.SeleccionarTaxaPublicacionOperationCompleted == null)) {
                this.SeleccionarTaxaPublicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarTaxaPublicacionOperationCompleted);
            }
            this.InvokeAsync("SeleccionarTaxaPublicacion", new object[] {
                        taxaid}, this.SeleccionarTaxaPublicacionOperationCompleted, userState);
        }
        
        private void OnSeleccionarTaxaPublicacionOperationCompleted(object arg) {
            if ((this.SeleccionarTaxaPublicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarTaxaPublicacionCompleted(this, new SeleccionarTaxaPublicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxa {
        
        private long idTaxaField;
        
        private string nombreField;
        
        private string nombreCortoField;
        
        private bool enEcuadorField;
        
        private bool endemicaField;
        
        private System.Nullable<long> idTaxaPadreField;
        
        private long idCatalogoField;
        
        private bool publicarEnWebField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        private System.Nullable<long> idPublicacionReporteField;
        
        private System.Nullable<int> anoField;
        
        private string pruebaField;
        
        /// <remarks/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCorto {
            get {
                return this.nombreCortoField;
            }
            set {
                this.nombreCortoField = value;
            }
        }
        
        /// <remarks/>
        public bool EnEcuador {
            get {
                return this.enEcuadorField;
            }
            set {
                this.enEcuadorField = value;
            }
        }
        
        /// <remarks/>
        public bool Endemica {
            get {
                return this.endemicaField;
            }
            set {
                this.endemicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdTaxaPadre {
            get {
                return this.idTaxaPadreField;
            }
            set {
                this.idTaxaPadreField = value;
            }
        }
        
        /// <remarks/>
        public long IdCatalogo {
            get {
                return this.idCatalogoField;
            }
            set {
                this.idCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public bool PublicarEnWeb {
            get {
                return this.publicarEnWebField;
            }
            set {
                this.publicarEnWebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdPublicacionReporte {
            get {
                return this.idPublicacionReporteField;
            }
            set {
                this.idPublicacionReporteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        public string prueba {
            get {
                return this.pruebaField;
            }
            set {
                this.pruebaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaxaPublicacion {
        
        private long idTaxaField;
        
        private long idPublicacionField;
        
        private bool principalField;
        
        private string nombreField;
        
        private string nombreCortoField;
        
        private string tituloField;
        
        private string tituloSecundarioField;
        
        private bool editorField;
        
        private string editorialField;
        
        private string volumenField;
        
        private long idPublicacionEnlaceField;
        
        private string nombreArchivoField;
        
        private string enlaceArchivoField;
        
        private bool descargaField;
        
        /// <remarks/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <remarks/>
        public long IdPublicacion {
            get {
                return this.idPublicacionField;
            }
            set {
                this.idPublicacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCorto {
            get {
                return this.nombreCortoField;
            }
            set {
                this.nombreCortoField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <remarks/>
        public string TituloSecundario {
            get {
                return this.tituloSecundarioField;
            }
            set {
                this.tituloSecundarioField = value;
            }
        }
        
        /// <remarks/>
        public bool Editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
            }
        }
        
        /// <remarks/>
        public string Editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
            }
        }
        
        /// <remarks/>
        public string Volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <remarks/>
        public long IdPublicacionEnlace {
            get {
                return this.idPublicacionEnlaceField;
            }
            set {
                this.idPublicacionEnlaceField = value;
            }
        }
        
        /// <remarks/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        public string EnlaceArchivo {
            get {
                return this.enlaceArchivoField;
            }
            set {
                this.enlaceArchivoField = value;
            }
        }
        
        /// <remarks/>
        public bool Descarga {
            get {
                return this.descargaField;
            }
            set {
                this.descargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void seleccionarTaxaCompletedEventHandler(object sender, seleccionarTaxaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarTaxaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarTaxaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void seleccionarTaxaPorIdCompletedEventHandler(object sender, seleccionarTaxaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarTaxaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarTaxaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SeleccionarTaxaPublicacionCompletedEventHandler(object sender, SeleccionarTaxaPublicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarTaxaPublicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarTaxaPublicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaxaPublicacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaxaPublicacion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591